getwd()
library(pheatmap)
library(RColorBrewer)
#setwd("/Users/kshitij/Desktop/Melbourne work/UNIMEL_DP/Analysis/CAT_BAT_analysis/Plutea_MAGs/New_Analysis/Metabolism/Enrichm_metabolic_selective_modules/")
setwd("/Users/kshitij/Desktop/Melbourne work/UNIMEL_DP/Analysis/CAT_BAT_analysis/Ipalifera_MAGs/Metabolism/enrichm_metabolic_KEGG_module75/")
data =read.table(file.choose(),sep="\t",header=T,row.names = 1)
head(data)
cols = colorRampPalette(c("white", "black"))(50)
data_tax=data.frame("Taxonomy"=c(rep("Alphaproteobacteria",37),rep("Bacteroidia",	5),rep("Binatia",1),rep("Chlorobia",	10),rep("Clostridia",	3),rep("Cyanobacteriia",	1),rep("Desulfarculia",	1),rep("Desulfobacteria",	4),rep("Gammaproteobacteria",	26),rep("Gemmatimonadetes",	2),rep("Phycisphaerae",	11),rep("Planctomycetes",	2),rep("SAR324",	4),rep("UBA11346",	1),rep("UBA1135",	1),rep("UBA4882",	1),rep("UBA9160",	3),rep("Vampirovibrionia",	1),rep("Verrucomicrobiae",3)))
rownames(data_tax)=rownames(data)
#newCols <- colorRampPalette(grDevices::stepped(length(unique(data_tax$Taxonomy))))
newCols<-colorRampPalette(hcl.colors(19,palette = "Purple-Orange"))
mycolors <- newCols(length(unique(data_tax$Taxonomy)))
names(mycolors) <- unique(data_tax$Taxonomy)
mycolors <- list(Taxonomy = mycolors)
pheatmap(t(data[,1:9]),cluster_rows = F,cluster_cols = F,cellwidth = 5,cellheight = 5,border_color = "white",fontsize = 4,gaps_col=c(37,42,43,53,56,57,58,62,88,90,101,103,107,108,109,110,113,114),gaps_row = c(5,8),color = cols,annotation_col=data_tax,annotation_colors = mycolors)

##### Ipalifera metabolism plot###############33
setwd("/Users/kshitij/Desktop/Melbourne work/UNIMEL_DP/Analysis/CAT_BAT_analysis/Ipalifera_MAGs/Metabolism/enrichm_metabolic_KEGG_module75/")
data =read.table(file.choose(),sep="\t",header=T,row.names = 1)
head(data)
cols = colorRampPalette(c("white", "black"))(50)
data_tax=data.frame("Taxonomy"=c(rep("Alphaproteobacteria",30),rep("Bacteroidia",	3),rep("Calditrichia",1),rep("Cyanobacteriia",	3),rep("Gammaproteobacteria",	10),rep("Gemmatimonadetes",	2),rep("Phycisphaerae",	6),rep("Planctomycetes",	8),rep("Sumerlaeia",	1),rep("UBA9160",	1),rep("Verrucomicrobiae",3),rep("WYAZ01",1)))
rownames(data_tax)=rownames(data)
#newCols <- colorRampPalette(grDevices::stepped(length(unique(data_tax$Taxonomy))))
newCols<-colorRampPalette(hcl.colors(19,palette = "Purple-Orange"))
mycolors <- newCols(length(unique(data_tax$Taxonomy)))
names(mycolors) <- unique(data_tax$Taxonomy)
mycolors <- list(Taxonomy = mycolors) 
pheatmap(t(data[,1:9]),cluster_rows = F,cluster_cols = F,cellwidth = 5,cellheight = 5,border_color = "white",fontsize = 4,gaps_col=c(30,33,34,37,47,49,55,63,64,65,68,69),gaps_row = c(5,8),color = cols,annotation_col=data_tax,annotation_colors = mycolors)


